version: "3.8"
services:
  backend: 
    build: ./
    depends_on:
      - database
    ports:
      - 4000:4000
    environment:
      MONGO_URL: mongodb://database:27017/node_app
      PORT: 4000
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017